### ISSUE TITLE
Failure to match long regexes

### ISSUE THREAD

**Issue by dhasenan** [Jimmy02020/find-in#1]
Test case:

```javascript
const find = require("find-in")['default'];
const fs = require("fs");

let flen = 64 * 1024 * 3;
let rlen = 64 * 1024;

let test = (i) => {
    let buf = Buffer.alloc(flen, ' ', 'utf8');
    buf.fill('B', i - 1, i + rlen + 1, 'utf8');
    buf.fill('A', i, i + rlen, 'utf8');
    fs.writeFileSync("test.txt", buf);
    find("test.txt", [/BA*B/], (err, report) => {
        let found = false;
        for (let r = 0; r < report.length; r++) {
            if (report[r].isFound) {
                found = true;
            }
        }
        if (!found) console.log(`${i}: missing`);
    });
};

test(10);
```

This probably can't be fixed to any reasonable degree. However, you could use a fixed chunk size or let people pass it in, advertising explicitly that you won't be able to handle anything longer than that.

**Comment by Jimmy02020** [comment]
Hey @dhasenan  
Thanks for this hardcore test
It passed the test when i increase the chunk size as you referred
passing a chunk size as an argument can solve it, but do you think that in real world we may have such matching size that can consume memory if we have more than regex request since it deals with an array of requests not a single one.
`[/BA*B/,/BA*B/,/BA*B/,/BA*B/,/BA*B/]`
